# Generated by Django 2.2.5 on 2019-11-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mycv', models.FileField(upload_to='PDFS/CVS/')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
